services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_api
      MYSQL_USER: sqluser
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      command: ./migration.sh
    depends_on:
      - database
    ports:
      - 6666:6666
