services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_api
      MYSQL_USER: sqluser
      MYSQL_PASSWORD: password
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 3000:3000
